INSERT INTO USER(USR_ID,USR_FIRST_NAME,USR_LAST_NAME, USR_BIRTH_DATE, USR_EMAIL)
VALUES(1,'John', 'Smith', null, 'johnSmith@email.com');

INSERT INTO USER(USR_ID,USR_FIRST_NAME,USR_LAST_NAME, USR_BIRTH_DATE, USR_EMAIL)
VALUES(2,'John2', 'Smith2', null, 'johnSmith2@email.com');

INSERT INTO BOOK(BK_ID, BK_NAME, BK_AUTHOR, BK_GENRE, BK_STATUS)
VALUES(1,'WIEDZIMIN', 'sdfdsfds', 'DRAMAT', 'A');

INSERT INTO BOOK(BK_ID, BK_NAME, BK_AUTHOR, BK_GENRE, BK_STATUS)
VALUES(2,'POTOP', 'sdfdsfds', 'DRAMAT', 'A');

INSERT INTO BOOK(BK_ID, BK_NAME, BK_AUTHOR, BK_GENRE, BK_STATUS)
VALUES(3,'HARRY POTTER', 'sdfdsfds', 'DRAMAT', 'A');

INSERT INTO LIBRARY(LIB_ID, LIB_BK_ID, LIB_QUANTITY, LIB_AVAILIBLE_QUANTITY)
VALUES(1, 1, 1, 1);

INSERT INTO LIBRARY(LIB_ID, LIB_BK_ID, LIB_QUANTITY, LIB_AVAILIBLE_QUANTITY)
VALUES(2, 3, 1, 1);

