CREATE TABLE USER (
        USR_ID INTEGER NOT NULL PRIMARY KEY,
        USR_FIRST_NAME VARCHAR(50) NOT NULL,
        USR_LAST_NAME VARCHAR(50) NOT NULL,
        USR_EMAIL VARCHAR2(50) NOT NULL,
        USR_BIRTH_DATE DATE
);

CREATE TABLE BOOK (
        BK_ID INTEGER NOT NULL PRIMARY KEY,
        BK_NAME VARCHAR(50) NOT NULL,
        BK_AUTHOR VARCHAR(50) NOT NULL,
        BK_GENRE VARCHAR(50) NOT NULL,
        BK_STATUS VARCHAR(50) NOT NULL
);

CREATE TABLE BOOK_ORDER (
    BKORD_ID INTEGER NOT NULL PRIMARY KEY,
    BKORD_BK_ID INTEGER NOT NULL,-- FOREIGN KEY REFERENCES BK_ID,
    BKORD_USR_ID INTEGER NOT NULL, --FOREIGN KEY REFERENCES USR_ID,
    BKORD_BOOKING_DATE DATE,
    BKORD_TYPE VARCHAR(1) NOT NULL,
);

CREATE TABLE LIBRARY (
    LIB_ID INTEGER NOT NULL PRIMARY KEY,
    LIB_BK_ID INTEGER NOT NULL,
    LIB_QUANTITY INTEGER NOT NULL,
    LIB_AVAILIBLE_QUANTITY INTEGER NOT NULL
);

CREATE TABLE BLACK_LIST (
    BLK_ID INTEGER NOT NULL PRIMARY KEY,
    BLK_USER_ID INTEGER NOT NULL,
    BLK_BOOK_ID INTEGER NOT NULL,
    BLK_BOOKING_DATE DATE,
    BLK_CASH_TO_PAY INTEGER
);